name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: node:16

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        npm install
    - name: Build App
      run: |
        npm run build
    - name: Start Server
      env:
        ENV_VAR_1: ${{ secrets.ENV_VAR_1 }}
        ENV_VAR_2: ${{ secrets.ENV_VAR_2 }}
      run: npm start --background
    - name: Wait for Server
      timeout-minutes: 5
      run: |
        start=$(date +%s)
        while ! nc -z localhost 3000; do
          now=$(date +%s)
          elapsed=$(expr $now - $start)
          if [ $elapsed -gt 300 ]; then
            echo "Server did not start in 5 minutes, exiting..."
            exit 1
          fi
          sleep 1
        done && echo "Server Started"
